apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Optional: specify or let Kubernetes assign one

